import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // typescript
      "typescript/adjacent-overload-signatures": "error",
      "typescript/array-type": ["warn", { default: "array" }],
      "typescript/no-explicit-any": "off",
      "typescript/explicit-module-boundary-types": "off",
      "typescript/no-empty-function": "off",
      "typescript/no-empty-interface": "off",
      "typescript/no-empty-object-type": "error",
      "typescript/no-restricted-types": ["error", {}],
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unused-vars": ["warn", {
        vars: "all",
        args: "after-used",
        ignoreRestSiblings: true,
        argsIgnorePattern: "(^_|h)"
      }],
      "typescript/no-wrapper-object-types": "error",
      // promise
      "promise/always-return": "off",
      "promise/no-return-wrap": "error",
      "promise/param-names": "error",
      "promise/catch-or-return": "off",
      "promise/no-native": "off",
      "promise/no-nesting": "off",
      "promise/no-promise-in-callback": "warn",
      "promise/no-callback-in-promise": "off",
      "promise/avoid-new": "off",
      "promise/no-new-statics": "error",
      "promise/no-return-in-finally": "warn",
      "promise/valid-params": "warn",
      // react
      // eslint
      "accessor-pairs": "error",
      "array-bracket-newline": ["error", "consistent"],
      "array-bracket-spacing": ["error", "never"],
      "array-callback-return": ["warn", { allowImplicit: true, checkForEach: false }],
      "array-element-newline": "off",
      "arrow-body-style": "off",
      "arrow-parens": ["error", "always"],
      "arrow-spacing": ["error", { before: true, after: true }],
      "block-scoped-var": "error",
      "block-spacing": ["error", "always"],
      "brace-style": ["error", "1tbs", { allowSingleLine: true }],
      "camelcase": "off",
      "capitalized-comments": "off",
      "class-methods-use-this": "off",
      "comma-dangle": ["warn", "always-multiline"],
      "comma-spacing": ["error", { before: false, after: true }],
      "comma-style": ["error", "last"],
      "complexity": "off",
      "computed-property-spacing": ["error", "never"],
      "consistent-return": "off",
      "consistent-this": ["warn", "self"],
      "constructor-super": "warn",
      "curly": ["error", "multi-line", "consistent"],
      "default-case": ["warn", { commentPattern: "^no\\sdefault" }],
      "dot-location": ["error", "property"],
      "dot-notation": "off",
      "eol-last": ["error", "always"],
      "eqeqeq": ["error", "always", { null: "ignore" }],
      "for-direction": "off",
      "func-call-spacing": ["off", "never"],
      "func-name-matching": ["warn", { considerPropertyDescriptor: true }],
      "func-names": "off",
      "func-style": ["warn", "declaration", { allowArrowFunctions: true }],
      "function-call-argument-newline": ["error", "consistent"],
      "function-paren-newline": ["error", "multiline-arguments"],
      "generator-star-spacing": ["error", {
        before: false,
        after: true,
        anonymous: "neither",
        method: { before: true, after: true }
      }],
      "getter-return": ["error", { allowImplicit: true }],
      "guard-for-in": "off",
      "handle-callback-err": ["error", "^(err|error)$"],
      "id-length": "off",
      "id-match": "off",
      "implicit-arrow-linebreak": ["error", "beside"],
      "indent-legacy": ["error", 2, { SwitchCase: 1, MemberExpression: 1 }],
      "indent": ["off", 2, { SwitchCase: 1, MemberExpression: 1 }],
      "init-declarations": "off",
      "jsx-quotes": ["error", "prefer-double"],
      "key-spacing": ["error", { beforeColon: false, afterColon: true, mode: "strict" }],
      "keyword-spacing": ["error", { before: true, after: true }],
      "line-comment-position": "off",
      "linebreak-style": ["warn", "unix"],
      "lines-around-comment": "off",
      "lines-around-directive": ["warn", { before: "never", after: "always" }],
      "lines-between-class-members": ["warn", "always", { exceptAfterSingleLine: true }],
      "max-depth": ["warn", 10],
      "max-len": "off",
      "max-lines": "off",
      "max-nested-callbacks": ["warn", 10],
      "max-params": ["warn", 10],
      "max-statements-per-line": ["error", { max: 5 }],
      "max-statements": "off",
      "multiline-comment-style": "off",
      "multiline-ternary": "off",
      "new-cap": "off",
      "new-parens": ["error", "always"],
      "newline-after-var": "off",
      "newline-before-return": "off",
      "newline-per-chained-call": "off",
      "no-alert": "warn",
      "no-array-constructor": "error",
      "no-await-in-loop": "warn",
      "no-bitwise": ["warn", { allow: ["~"], int32Hint: true }],
      "no-buffer-constructor": "error",
      "no-caller": "error",
      "no-case-declarations": "off",
      "no-catch-shadow": "warn",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-confusing-arrow": "off",
      "no-console": "error",
      "no-const-assign": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-continue": "off",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-div-regex": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-else-return": ["warn", { allowElseIf: false }],
      "no-empty-character-class": "error",
      "no-empty-function": "off",
      "no-empty-pattern": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-eq-null": "off",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-label": "error",
      "no-extra-parens": ["error", "functions"],
      "no-extra-semi": "error",
      "no-fallthrough": "off",
      "no-floating-decimal": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-inline-comments": "off",
      "no-inner-declarations": ["error", "functions"],
      "no-invalid-regexp": "error",
      "no-invalid-this": "off",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": ["error", { allowLoop: false, allowSwitch: false }],
      "no-lone-blocks": "error",
      "no-lonely-if": "off",
      "no-loop-func": "off",
      "no-magic-numbers": "off",
      "no-mixed-operators": ["error", {
        groups: [["==", "!=", "===", "!==", ">", ">=", "<", "<="], ["&&", "||"], ["in", "instanceof"]],
        allowSamePrecedence: true
      }],
      "no-mixed-requires": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-multi-assign": "off",
      "no-multi-spaces": "error",
      "no-multi-str": "error",
      "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0 }],
      "no-native-reassign": "error",
      "no-negated-condition": "off",
      "no-negated-in-lhs": "error",
      "no-nested-ternary": "off",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-require": "error",
      "no-new-symbol": "error",
      "no-new-wrappers": "error",
      "no-new": "off",
      "no-obj-calls": "error",
      "no-octal-escape": "error",
      "no-octal": "error",
      "no-param-reassign": "off",
      "no-path-concat": "error",
      "no-plusplus": "off",
      "no-process-env": "error",
      "no-process-exit": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-restricted-globals": "off",
      "no-restricted-imports": "off",
      "no-restricted-modules": "off",
      "no-restricted-properties": "off",
      "no-restricted-syntax": "off",
      "no-return-assign": ["warn", "except-parens"],
      "no-return-await": "off",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow-restricted-names": "error",
      "no-shadow": "off",
      "no-sparse-arrays": "error",
      "no-sync": "off",
      "no-tabs": "error",
      "no-template-curly-in-string": "error",
      "no-ternary": "off",
      "no-this-before-super": "error",
      "no-throw-literal": "error",
      "no-trailing-spaces": "off",
      "no-undef-init": "error",
      "no-undef": "off",
      "no-undefined": "off",
      "no-underscore-dangle": "off",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": ["error", { defaultAssignment: false }],
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unused-expressions": "off",
      "no-unused-labels": "error",
      "no-unused-vars": "off",
      "no-use-before-define": "off",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-whitespace-before-property": "error",
      "no-var": "warn",
      "no-void": "error",
      "no-warning-comments": "off",
      "no-with": "error",
      "nonblock-statement-body-position": ["error", "below"],
      "object-curly-newline": ["error", { multiline: true, consistent: true }],
      "object-curly-spacing": "off",
      "object-property-newline": ["error", { allowMultiplePropertiesPerLine: true }],
      "object-shorthand": ["error", "always"],
      "one-var-declaration-per-line": "off",
      "one-var": "off",
      "operator-assignment": ["warn", "always"],
      "operator-linebreak": ["error", "before"],
      "padded-blocks": ["error", { blocks: "never", switches: "never", classes: "never" }],
      "padding-line-between-statements": "off",
      "prefer-arrow-callback": ["warn", { allowNamedFunctions: false, allowUnboundThis: false }],
      "prefer-const": ["warn", { destructuring: "any", ignoreReadBeforeAssign: false }],
      "prefer-destructuring": "off",
      "prefer-numeric-literals": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-reflect": "off",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "warn",
      "quote-props": ["warn", "as-needed", { unnecessary: false }],
      "quotes": "off",
      "radix": ["error", "as-needed"],
      "require-await": "error",
      "require-jsdoc": "off",
      "require-yield": "error",
      "rest-spread-spacing": ["error", "never"],
      "semi-spacing": ["error", { before: false, after: true }],
      "semi-style": ["error", "last"],
      "semi": "off",
      "sort-imports": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "space-before-blocks": ["error", "always"],
      "space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
      "space-in-parens": ["error", "never"],
      "space-infix-ops": ["error", { int32Hint: true }],
      "space-unary-ops": ["error", { words: true, nonwords: false }],
      "spaced-comment": ["error", "always", {
        line: { markers: ["*package", "!", "/", ","] },
        block: { balanced: true, markers: ["*package", "!", ",", ":", "::", "flow-include"], exceptions: ["*"] }
      }],
      "strict": "off",
      "switch-colon-spacing": ["error", { before: false, after: true }],
      "symbol-description": "error",
      "template-curly-spacing": ["error", "never"],
      "template-tag-spacing": ["error", "never"],
      "unicode-bom": ["error", "never"],
      "use-isnan": "error",
      "valid-jsdoc": "off",
      "valid-typeof": "off",
      "vars-on-top": "off",
      "wrap-iife": ["error", "any", { functionPrototypeMethods: true }],
      "wrap-regex": "off",
      "yield-star-spacing": ["error", "after"],
      "yoda": ["error", "never", { exceptRange: true }]
    }
  },
])
