services:
  postgres:
    image: postgres:15
    container_name: recipe-postgres
    environment:
      POSTGRES_USER: recipeuser
      POSTGRES_PASSWORD: recipepass
      POSTGRES_DB: recipedb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/actuator/health" ]
      interval: 30s          # Проверять каждые 30 секунд
      timeout: 10s           # Ждать ответа не более 10 секунд
      retries: 3             # 3 неудачи = контейнер unhealthy
      start_period: 40s      # Дать 40 секунд на старт приложения перед проверками
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data: