spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  token:
    expiration: 24h

app:
  frontend-base-url: "https://recipes-app-t1kp.vercel.app"
  password-reset-ttl-minutes: 30
  rate-limit-max-requests-per-hour: 3