spring.profiles.active=dev

# for production
# spring.profiles.active=prod

jwt.secret=${JWT_SECRET:x3BSPl2F6tZlwXxFAkGBvB5pulyf7ABPtwUdPOL6Zws=}
jwt.token-expiration=24h

server.servlet.context-path=/api