spring:
  application:
    name: recipe.app
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    default-charset: UTF-8
    jndi-name: null

server:
  port: 8080
  servlet:
    context-path: /api


