spring:
  application:
    name: recipe.app
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/recipedb
    username: recipeuser
    password: recipepass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev #or prod
server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:x3BSPl2F6tZlwXxFAkGBvB5pulyf7ABPtwUdPOL6Zws=}
  token:
    expiration: 24h
